name: PalworldArchiveRepair Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get last commit time
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%cd --date=format:'%Y%m%d%H%M%S' main)
          echo "LAST_COMMIT_TIME=${LAST_COMMIT_TIME}" >> $GITHUB_ENV
      - name: Build and push
        env:
          DOCKER_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/palworld-archive-repair:latest
          DOCKER_STABLE: ${{ secrets.DOCKERHUB_USERNAME }}/palworld-archive-repair:${{ env.LAST_COMMIT_TIME }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            $DOCKER_LATEST
            $DOCKER_STABLE
